services:
  aerospike:
    image: aerospike:ce-8.1.0.3_1
    container_name: aerospike
    ports:
      - "18710:3000"
      - "18711:3001"
      - "18712:3002"
    shm_size: 1g
    environment:
      NAMESPACE: test
      DEFAULT_TTL: "2592000"
      ACCESS_PORT: "18710"
    volumes:
      - ./scripts/aerospike.template.conf:/etc/aerospike/aerospike.template.conf

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
