services:
  aerospike:
    image: aerospike:ce-8.1.0.3_1
    container_name: aerospike
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    cpus: 2
    mem_limit: 2g
    shm_size: 1g
    environment:
      NAMESPACE: test
      DEFAULT_TTL: "2592000"
    volumes:
      - ./scripts/aerospike.template.conf:/etc/aerospike/aerospike.template.conf
