"""Type stubs for aerospike.predicates module."""

from typing import Union

def equals(bin_name: str, val: Union[int, str]) -> tuple[str, ...]: ...
def between(bin_name: str, min_val: int, max_val: int) -> tuple[str, ...]: ...
def contains(
    bin_name: str, index_type: int, val: Union[int, str]
) -> tuple[str, ...]: ...
def geo_within_geojson_region(
    bin_name: str, geojson: str
) -> tuple[str, ...]: ...
def geo_within_radius(
    bin_name: str, lat: float, lng: float, radius: float
) -> tuple[str, ...]: ...
def geo_contains_geojson_point(
    bin_name: str, geojson: str
) -> tuple[str, ...]: ...
