from typing import Any

def get_memory_stats() -> dict[str, int]: ...
def reset_memory_stats() -> None: ...

class MemoryProfiler:
    def __enter__(self) -> MemoryProfiler: ...
    def __exit__(self, *args: Any) -> None: ...
    @property
    def allocated_bytes(self) -> int: ...
    @property
    def deallocated_bytes(self) -> int: ...
    @property
    def delta_bytes(self) -> int: ...
    @property
    def allocation_count(self) -> int: ...
