from dataclasses import dataclass
from typing import Any, Optional

@dataclass
class TelemetryConfig:
    enabled: Optional[bool] = ...
    log_level: str = ...
    tracing_enabled: bool = ...
    metrics_enabled: bool = ...
    tracer_provider: Any = ...
    meter_provider: Any = ...
    request_hook: Any = ...
    response_hook: Any = ...
    error_hook: Any = ...

def configure_telemetry(config: TelemetryConfig | None = None) -> None: ...
def shutdown_telemetry() -> None: ...
